### PR TITLE
Pretty-printing of LLVMVals

### LINKED ISSUE #210: Pretty-printing of LLVMVal
SAWscript's `matchArg` attempts to compare `LLVMVal`s with SAW's `SetupValues`. It would be nice if we could print `LLVMVal`s when this comparison fails (at least the concrete parts).

### PR DESCRIPTION
**Pull request by siddharthist**
Fixes #210

### CODE REVIEW

File: crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Value.hs [hunk 1]
```diff
@@ -40,6 +40,7 @@ import           Control.Monad (foldM, join)
 import           Data.Foldable (toList)
 import           Data.Maybe (mapMaybe)
 import           Data.List (intersperse)
+import qualified Text.PrettyPrint.ANSI.Leijen as PP
 
 import           Data.Parameterized.Classes
```
Comment (siddharthist) [inline crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Value.hs]:
```suggestion
import           Data.Parameterized.Class
```

File: crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Value.hs [hunk 2]
```diff
@@ -123,6 +124,56 @@ zeroInt sym bytes k
...
+  pretty =
+    let typed doc tp = PP.text doc PP.<+> PP.text ":" PP.<+> PP.text (show tp)
+    in
+      \case
+        (LLVMValZero tp) -> PP.angles (typed "zero" tp)
+        (LLVMValUndef tp) -> PP.angles (typed "undef" tp)
+        (LLVMValInt blk w) ->
+          case asNat blk of
+            Just 0 ->
+              case (asUnsignedBV w, asSignedBV w) of
```
Comment (robdockins) [inline crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Value.hs]: Probably better to just case on `asUnsignedBV` and use `toSigned` to get the signed value instead of casing separately.
