### PR TITLE
Sequences

### LINKED ISSUE #587: Incorrect counterexample in `crux-llvm`
Given `test.c`:
```c
#include <crucible.h>
#define N 2

int main()
{
    int i;
    for (i = 1; i <= N; i++) {
      int i0 = i;
      for (int j = 1; j <= i0; j++) {
        int b = crucible_int32_t("b");
        switch (b) {
	  case 1: break;
	  case 2: i++; break;
	  default:
	    return i;
	}
      }
    }
    crucible_assert(i <= 4, __FILE__, __LINE__);

    return 0;
}
```
Running `crux-llvm test.c` produces a counter example file whose contents include:
```c
size_t const crucible_values_number_int32_t = 4;
const char* crucible_names_int32_t[] = { "b","b","b","b" };
int32_t const crucible_values_int32_t[] = { 0x1,0x2,0x0,0x2 };
```
However this is not a valid counter-example, as executing the program with this input results in returning from `main` before hitting the assertion.  Instead, the counterexample should have the value `0x2` as the third entry:
```c
int32_t const crucible_values_int32_t[] = { 0x1,0x2,0x2,0x2 };
```

### PR DESCRIPTION
**Pull request by robdockins**
Add a new `Sequence` type to crucible.

This will be used to implement the event log needed to close #587.  It may also prove helpful when we eventualy refactor the LLVM memory model.

### CODE REVIEW

File: crucible/src/Lang/Crucible/Simulator/SymSequence.hs [hunk 1]
```diff
@@ -0,0 +1,302 @@
...
+import qualified Data.Parameterized.Map as MapF
+
+import           Lang.Crucible.Types
+import           What4.Interface
+import           What4.Partial
+
+------------------------------------------------------------------------
+-- SymSequence
+
+data SymSequence sym a where
```
Comment (RyanGlScott) [inline crucible/src/Lang/Crucible/Simulator/SymSequence.hs:36]: It might be worth giving this a `Show`/`ShowF`/`Pretty` instance to make it easier to print these for debugging purposes in the future.

File: crucible-syntax/test-data/simulator-tests/seq-test1.cbl [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+    (assert! (equal? 0 (seq-length n)) "nil length test")
+
+    (let s1 (seq-cons 5 n))
+
+    (assert! (not (seq-nil? s1)) "cons test")
+    (assert! (equal? 1 (seq-length s1)) "cons length test")
+
+    (let v (from-just (seq-head s1) "head s1"))
+    (let t (from-just (seq-tail s1) "tail s1"))
+    (let u (from-just (seq-uncons s1) "uncons s1"))
```
Comment (RyanGlScott) [inline crucible-syntax/test-data/simulator-tests/seq-test1.cbl:14]: I don't think there's any `assert!`/`print` statement involving this `u` value. I think it would be worthwhile to add one for consistency with the other operations featured in this test case.

**Review by RyanGlScott — COMMENTED** [review]
Hooray! This looks good to me from a quick glance (aside from some very minor suggestions).

File: crucible/src/Lang/Crucible/Simulator/RegValue.hs [hunk 3]
```diff
@@ -143,6 +148,7 @@ instance Show (FnVal sym a r) where
 -- | Version of 'MuxFn' specialized to 'RegValue'
 type ValMuxFn sym tp = MuxFn (Pred sym) (RegValue sym tp)
 
+
```
[the remark this answers is not in the document]
Comment (robdockins) [reply crucible/src/Lang/Crucible/Simulator/RegValue.hs:151]: nope

File: crucible/src/Lang/Crucible/Simulator/SymSequence.hs (hunk 1 above)
Comment (robdockins) [reply crucible/src/Lang/Crucible/Simulator/SymSequence.hs:36]: agreed

File: crucible-syntax/test-data/simulator-tests/seq-test1.cbl (hunk 2 above)
Comment (robdockins) [reply crucible-syntax/test-data/simulator-tests/seq-test1.cbl:14]: Absolutely.  Turns out, I have to implement syntax for structs first, which is why I stopped here for now. :-)

File: crucible-syntax/src/Lang/Crucible/Syntax/Atoms.hs [hunk 4]
```diff
@@ -50,7 +49,7 @@ data Keyword = Defun | DefBlock | DefGlobal
              | Just_ | Nothing_ | FromJust
              | Inj | Proj
              | AnyT | UnitT | BoolT | NatT | IntegerT | RealT | ComplexRealT | CharT | StringT
-             | BitvectorT | VectorT | FPT | FunT | MaybeT | VariantT | RefT
+             | BitvectorT | VectorT | SequenceT | FPT | FunT | MaybeT | VariantT | StructT | RefT
```
Comment (RyanGlScott) [inline crucible-syntax/src/Lang/Crucible/Syntax/Atoms.hs:52]: The `crucible-syntax` README ought to be updated in light of these new types being introduced. (At the very least, the "Types" section.)

File: crucible/src/Lang/Crucible/Simulator/SymSequence.hs [hunk 5]
```diff
@@ -0,0 +1,507 @@
...
+    loop SymSequenceNil = pure []
+    loop (SymSequenceCons _ v tl) = (:) <$> eval v <*> loop tl
+    loop (SymSequenceAppend _ xs ys) = (++) <$> loop xs <*> loop ys
+    loop (SymSequenceMerge _ p xs ys) =
+      do b <- conc p
+         if b then loop xs else loop ys
+
+-- | Given a pretty printer for elements,
+--   print a symbolic sequence.
+prettySymSequence :: IsExpr (SymExpr sym) =>
```
Comment (RyanGlScott) [inline crucible/src/Lang/Crucible/Simulator/SymSequence.hs:402]: Would it be more convenient to also have a `Pretty` instance with `pretty = prettySymSequence pretty`?

**Review by RyanGlScott — APPROVED** [review]
