### PR TITLE
crucible-mir: fix Crucible signature of `extern "rust-call"` functions

### LINKED ISSUE #1222: `crucible-mir` crashes due to improperly constructing vtable shim types
I've installed saw and `mir-json` on my system, and I think I have the right version of everything set up.

```
$ saw --version
1.1
$ saw-rustc --version
test build - extract output path - ["rustc", "--version", "--test", "--target", "aarch64-apple-darwin", "--cfg", "crux", "-L", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--sysroot", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs"]
rustc 1.69.0-nightly (5e37043d6 2023-01-22)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/mir-json-rustc-wrapper.rs:86:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(kind of weird version is panicking but you can see the rustc version is correct in there)

When I try to compile the following:

```
fn add(x: u32, y: u32) -> u32 {
x + y
}
```

it works fine, I'm able to handle it with the following saw script:

```
enable_experimental;

m <- mir_load_module "hello.linked-mir.json";
```

then I run `saw-rustc`, which succeeds

```
$ saw-rustc hello.rs
test build - extract output path - ["rustc", "hello.rs", "--test", "--target", "aarch64-apple-darwin", "--cfg", "crux", "-L", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--sysroot", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs"]
test build - ["rustc", "hello.rs", "--target", "aarch64-apple-darwin", "--cfg", "crux", "-L", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--sysroot", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--cfg", "crux_top_level", "--crate-type", "rlib"]
warning: function `add` is never used
 --> hello.rs:1:4
  |
1 | fn add(x: u32, y: u32) -> u32 {
  |    ^^^
  |
  = note: `#[warn(dead_code)]` on by default

note: Emitting MIR for hello/a2764e5c::add

warning: 1 warning emitted

linking 19 mir files into hello.linked-mir.json
  inputs: libhello.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libstd.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcore.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/liballoc.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcrucible.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/liblibc.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libunwind.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libadler.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libgimli.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libobject.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libmemchr.mir
generated test script hello
```

when I run saw on this, it succeeds, telling me my installation is at least somewhat working:

```
$ saw hello.saw
[17:24:19.173] Loading file "/Users/sarah.spall/projects/provers/aes_rust_colin/src/hello.saw"
```

however, if I then try a more complicated function that uses IO, like the following:

```
fn main() {
println!("hello world");
}
```

I can compile this with `saw-rustc`:

```
test build - extract output path - ["rustc", "hello.rs", "--test", "--target", "aarch64-apple-darwin", "--cfg", "crux", "-L", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--sysroot", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs"]
test build - ["rustc", "hello.rs", "--target", "aarch64-apple-darwin", "--cfg", "crux", "-L", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--sysroot", "/Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs", "--cfg", "crux_top_level", "--crate-type", "rlib"]
warning: function `main` is never used
 --> hello.rs:1:4
  |
1 | fn main() {
  |    ^^^^
  |
  = note: `#[warn(dead_code)]` on by default

note: Emitting MIR for hello/7d20a575::main

note: Emitting MIR for hello/7d20a575::main::{{promoted}}[0]

note: Emitting MIR for hello/7d20a575::main::{{promoted}}[1]

note: Emitting ADT definition for core/0a2bb85a::fmt::Arguments::_adtbd21306cbe4f0b9b[0]

note: Emitting ADT definition for core/0a2bb85a::fmt::ArgumentV1::_adtbd21306cbe4f0b9b[0]

note: Emitting MIR for core/0a2bb85a::fmt::{impl#4}::new_v1::_instbd21306cbe4f0b9b[0]

note: Emitting MIR for core/0a2bb85a::fmt::{impl#4}::new_v1::_instbd21306cbe4f0b9b[0]::{{promoted}}[0]

note: Emitting MIR for core/0a2bb85a::fmt::{impl#4}::new_v1::_instbd21306cbe4f0b9b[0]::{{promoted}}[1]

note: Emitting ADT definition for core/0a2bb85a::option::Option::_adt9c34ccba92936212[0]

note: Emitting ADT definition for core/0a2bb85a::fmt::rt::v1::Argument::_adtb7803c2264daf0ec[0]

note: Emitting ADT definition for core/0a2bb85a::result::Result::_adtb3f4e538b15dbdda[0]

note: Emitting ADT definition for core/0a2bb85a::fmt::Formatter::_adtbd21306cbe4f0b9b[0]

note: Emitting ADT definition for core/0a2bb85a::fmt::Error::_adtb7803c2264daf0ec[0]

note: Emitting ADT definition for core/0a2bb85a::marker::PhantomData::_adta595c6a450ad127c[0]

note: Emitting ADT definition for core/0a2bb85a::crucible::any::Any::_adtb7803c2264daf0ec[0]

note: Emitting trait def for Some(dyn std::fmt::Write)

note: Emitting ADT definition for core/0a2bb85a::fmt::rt::v1::FormatSpec::_adtb7803c2264daf0ec[0]

note: Emitting ADT definition for core/0a2bb85a::fmt::rt::v1::Alignment::_adtb7803c2264daf0ec[0]

note: Emitting ADT definition for core/0a2bb85a::option::Option::_adtaffa7a8b1157c078[0]

note: Emitting ADT definition for core/0a2bb85a::fmt::rt::v1::Count::_adtb7803c2264daf0ec[0]

warning: 1 warning emitted

linking 19 mir files into hello.linked-mir.json
  inputs: libhello.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libstd.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcore.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/liballoc.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcrucible.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/liblibc.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libunwind.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libadler.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libgimli.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libobject.mir /Users/sarah.spall/projects/provers/crucible/crux-mir/rlibs_real/lib/rustlib/aarch64-apple-darwin/lib/libmemchr.mir
generated test script hello
```

(and I can provide this mir file if it might be useful). When I run `saw hello.saw` (same saw file) again for this example I get

```
[17:26:51.993] Loading file "/Users/sarah.spall/projects/provers/aes_rust_colin/src/hello.saw"
[17:26:54.234] vtable signature mismatch for vtable core/0a2bb85a::ops[0]::function[0]::FnMut[0]::_vtblb704da9d5ff2e622[0] of trait core/0a2bb85a::ops[0]::function[0]::FnMut[0]::_trait1f2906ad28e660ae[0] : StructRepr [FunctionHandleRepr [AnyRepr, StructRepr [MaybeRepr (IntrinsicRepr MirReference [AnyRepr])]] UnitRepr, FunctionHandleRepr [AnyRepr, IntrinsicRepr MirReference [AnyRepr]] UnitRepr] != StructRepr [FunctionHandleRepr [AnyRepr, StructRepr [MaybeRepr (IntrinsicRepr MirReference [AnyRepr])]] UnitRepr, FunctionHandleRepr [AnyRepr, StructRepr [MaybeRepr (IntrinsicRepr MirReference [AnyRepr])]] UnitRepr]
CallStack (from HasCallStack):
  error, called at src/Mir/Trans.hs:980:20 in crucible-mir-0.2-inplace:Mir.Trans
  mkTraitObject, called at src/Mir/Trans.hs:823:11 in crucible-mir-0.2-inplace:Mir.Trans
  evalCast', called at src/Mir/Trans.hs:954:5 in crucible-mir-0.2-inplace:Mir.Trans
  evalCast, called at src/Mir/Trans.hs:1011:30 in crucible-mir-0.2-inplace:Mir.Trans
  evalRval, called at src/Mir/Trans.hs:1246:11 in crucible-mir-0.2-inplace:Mir.Trans
  transStatement, called at src/Mir/Trans.hs:1712:68 in crucible-mir-0.2-inplace:Mir.Trans
  translateBlockBody, called at src/Mir/Trans.hs:1721:28 in crucible-mir-0.2-inplace:Mir.Trans
  registerBlock, called at src/Mir/Trans.hs:1761:10 in crucible-mir-0.2-inplace:Mir.Trans
  genFn, called at src/Mir/Trans.hs:1807:24 in crucible-mir-0.2-inplace:Mir.Trans
  transDefine, called at src/Mir/Trans.hs:2264:30 in crucible-mir-0.2-inplace:Mir.Trans
  transCollection, called at src/Mir/ParseTranslate.hs:76:26 in crucible-mir-0.2-inplace:Mir.ParseTranslate
  translateMIR, called at src/SAWScript/Crucible/MIR/Builtins.hs:528:11 in saw-script-1.1-inplace:SAWScript.Crucible.MIR.Builtins
```

Any troubleshooting tips / suggestions? is my installation borked or is something else wrong with the way I'm doing things

### PR DESCRIPTION
**Pull request by spernsteiner**
The unstable `extern "rust-call"` ABI used for closures is normally compiled by untupling the last argument: `extern "rust-call" fn(T, (U, V))` is compiled roughly the same as `fn(T, U, V)`.  Some parts of rustc's MIR code generation depend on this equivalence to perform operations that would otherwise be invalid.  This branch replaces our previous workaround (the "`spread_arg` hack") with a new implementation that behaves more like rustc's existing backends.  In particular, with this branch, the tupled and untupled signatures now map to the same Crucible function signature.  This also lets us add support for calling closures through `&dyn Fn`.

With this change, the handling of `extern "rust-call"` functions in crux-mir is more consistent, but there is still one tricky case.  At the MIR level, `extern "rust-call"` functions are normally defined with a tupled signature and called by passing a tuple of arguments.  However, the implementation functions of closures (e.g. for `|x| x + 1`, the MIR function that computes `x + 1`) are defined with an untupled signature, but are still passed a tuple at the call site.  This case is detected by looking for the combination of `"abi": {"kind": "RustCall"}` and `"spread_arg": null` on the function definition, and it's handled separately from `RustCall` with non-null `spread_arg` in some places.

Fixes #1222

### CODE REVIEW

File: crucible-mir/src/Mir/Mir.hs [hunk 1]
```diff
@@ -133,28 +133,33 @@ data FnSig = FnSig {
...
+    -- field is unset.  This applies to closure implementations, which are
+    -- are `extern "rust-call"` and are called with tupled arguments, but are
+    -- defined with un-tupled arguments (and no `spread_arg`).  For such
+    -- functions, `fsarg_tys` will contain the un-tupled arguments, and the ABI
+    -- will be `RustCall RcNoSpreadArg`.
+    | RcSpreadArg Int
+    -- ^ The `FnSig` is associated with a body, and the body has a `spread_arg`
+    -- index.  This applies to various `extern "rust-call"` closure-related
+    -- shims and vtable methods, which are both called and defined with a
+    -- tupled signature.
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/Mir.hs]: Haddock nit pick: surrounding something with backticks causes Haddock to try and hyperlink it as if it were a Haskell identifier. Use `@...@` for general monospace text:

```suggestion
    = RcNoBody
    -- ^ The `FnSig` containing this `RustCall` `Abi` isn't the signature of a
    -- `Fn` body.  For example, @extern \"rust-call\"@ function pointers always
    -- have an ABI of @`RustCall` `RcNoBody`@.
    | RcNoSpreadArg
    -- ^ The `FnSig` is associated with a body, but the body's @spread_arg@
    -- field is unset.  This applies to closure implementations, which are
    -- are @extern \"rust-call\"@ and are called with tupled arguments, but are
    -- defined with un-tupled arguments (and no @spread_arg@).  For such
    -- functions, @fsarg_tys@ will contain the un-tupled arguments, and the ABI
    -- will be `RustCall RcNoSpreadArg`.
    | RcSpreadArg Int
    -- ^ The `FnSig` is associated with a body, and the body has a @spread_arg@
    -- index.  This applies to various @extern \"rust-call\"@ closure-related
    -- shims and vtable methods, which are both called and defined with a
    -- tupled signature.
```

Also, you have to escape double quotes, since Haddock treats `"..."` as though you are trying to hyperlink a Haskell module name.

File: crucible-mir/src/Mir/JSON.hs [hunk 2]
```diff
@@ -232,10 +230,17 @@ instance FromJSON Collection where
 instance FromJSON Fn where
     parseJSON = withObject "Fn" $ \v -> do
       args <- v .: "args"
+      abi <- v .: "abi" >>= \abi -> case abi of
+        RustCall _ -> do
+          spreadArg <- v .: "spread_arg"
+          case spreadArg of
+            Just i -> return $ RustCall (RcSpreadArg i)
+            Nothing -> return $ RustCall RcNoSpreadArg
+        _ -> return abi
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/JSON.hs]: There's a lot of infix operators on the `abi <- v .: "abi" >>= \abi -> case abi of` line. How about splitting this up a bit:

```hs
      abi <- v .: "abi"
      let abi' =
            case abi of
              RustCall _ -> do
                spreadArg <- v .: "spread_arg"
                case spreadArg of
                  Just i -> return $ RustCall (RcSpreadArg i)
                  Nothing -> return $ RustCall RcNoSpreadArg
              _ -> return abi
```

File: crucible-mir/src/Mir/PP.hs [hunk 3]
```diff
@@ -135,12 +135,15 @@ pretty_temp (Var vn vm vty _vzst) =
...
-      vcat $ [pretty "fn" <+> pretty fname1 <> tupled (map pretty_arg fargs1)
+      vcat $ [extern <> pretty "fn" <+> pretty fname1 <> tupled (map pretty_arg fargs1)
                   <+> arrow <+> pretty rty <+> lbrace]
             ++ [indent 3 (pretty fbody1),
                 rbrace]
       where
         rty    = fs^.fsreturn_ty
+        extern = case fs^.fsabi of
+          RustAbi -> mempty
+          abi -> pretty "extern" <+> viaShow abi <+> mempty
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/PP.hs:146]: If I understand correctly, `viaShow abi` will cause `extern "rust-call" ...` to be pretty-printed as something like `extern RustCall RcNoBody ...`, which doesn't seem desirable. Perhaps we should call `pretty abi` and change the `Pretty Abi` instance to render `RustCall ...` as `"rust-call"`?

File: crucible-mir/src/Mir/TransTy.hs [hunk 4]
```diff
@@ -314,6 +315,26 @@ isZeroSized col ty = go ty
       _ -> False
 
 
+-- | Get the "ABI-level" function arguments for `sig`, which determines the
+-- arguments we use for the Crucible `FnHandle`.  This applies a special
+-- adjustment for `extern "rust-call"` functions, like the one rustc applies
+-- when converting a `FnSig` to `FnAbi`.
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/TransTy.hs]:
```suggestion
-- | Get the \"ABI-level\" function arguments for @sig@, which determines the
-- arguments we use for the Crucible `FnHandle`.  This applies a special
-- adjustment for @extern \"rust-call\"@ functions, like the one rustc applies
-- when converting a `FnSig` to `FnAbi`.
```

File: crucible-mir/src/Mir/TransTy.hs [hunk 5]
```diff
@@ -314,6 +315,26 @@ isZeroSized col ty = go ty
...
+  M.RustCall (M.RcSpreadArg _) -> untupledArgs
+  _ -> normalArgs
+  where
+    normalArgs = sig ^. M.fsarg_tys
+    untupledArgs = case normalArgs of
+      [M.TyTuple tys] -> tys
+      [selfTy, M.TyTuple tys] -> selfTy : tys
+      _ -> error $
+          "unexpected argument list for " ++ show (sig ^. M.fsabi) ++  ": "
+            ++ show (sig ^. M.fsarg_tys)
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/TransTy.hs]: Consider using `show (pretty ...)` instead of `show ...` here to make the results a bit more compact and human-readable.

File: crucible-mir/src/Mir/Trans.hs [hunk 6]
```diff
@@ -2621,6 +2647,13 @@ transCollection col halloc = do
     hmap2 <- mkShimHandleMap col halloc
     let hmap = hmap1 <> hmap2
 
+    --forM_ (Map.toList hmap) $ \(name, mh) -> do
+    --  MirHandle _ sig handle <- return mh
+    --  traceM $ "function " ++ show name ++ ":"
+    --  traceM $ "  sig = " ++ show sig
+    --  traceM $ "  handle = " ++ show (FH.handleType handle)
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/Trans.hs]: Perhaps we should always print this if the `debugLevel` (from `MirGenerator`) is high enough?

File: crucible-mir/src/Mir/Trans.hs [hunk 7]
```diff
@@ -2005,27 +2033,29 @@ genFn (M.Fn fname argvars _ body@(MirBody localvars blocks _)) rettype inputs =
...
-            (Ctx.AssignExtend inputs' input, var : vars') -> do
+        case (inputs, vars) of
+            ([], []) -> return ()
+            (input : inputs', var : vars') -> do
                 mvi <- use $ varMap . at (var ^. varname)
                 Some vi <- case mvi of
                     Just x -> return x
                     Nothing -> mirFail $ "no varinfo for arg " ++ show (var ^. varname)
-                Refl <- testEqualityOrFail (R.typeOfAtom input) (varInfoRepr vi) $
+                MirExp inputTpr inputExpr <- return input
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/Trans.hs]: Consider pattern-matching directly on `input` to avoid this `return input` statement:

```hs
            (MirExp inputTpr inputExpr : inputs', var : vars') -> do
```

File: crucible-mir/src/Mir/Trans.hs [hunk 8]
```diff
@@ -1880,6 +1880,7 @@ initLocals localVars addrTaken = forM_ localVars $ \v -> do
         Just (MirExp tpr' val) -> do
             Refl <- testEqualityOrFail tpr tpr' $
                 "initialValue produced " ++ show tpr' ++ " instead of " ++ show tpr
+                  ++ ", for " ++ show ty
```
Comment (RyanGlScott) [inline crucible-mir/src/Mir/Trans.hs]: Slightly more compact:

```suggestion
                  ++ ", for " ++ show (pretty ty)
```

**Review by RyanGlScott — COMMENTED** [review]
Does this fix https://github.com/GaloisInc/crucible/issues/1222? If so, can one or more of the programs from that issue be added as a `crux-mir` regression test?

File: crucible-mir/src/Mir/Mir.hs (hunk 1 above)
Comment (samcowger) [reply crucible-mir/src/Mir/Mir.hs]: I think the fact that the string is hyphenated will actually stop Haddock from trying to turn it into a link - though the reference is [a bit vague](https://haskell-haddock.readthedocs.io/latest/markup.html#linking-to-modules) on the rules for such links:
> A basic check is done on the syntax of the header name to ensure that it is valid before turning it into a link

Comment (RyanGlScott) [reply crucible-mir/src/Mir/Mir.hs]: Ah, I learned something today. I tried running Haddock on `@extern "rust-call"@`, and sure enough, it rendered the way I expected to. In that case, I'm fine with not escaping the double quotes here.

File: crucible-mir/src/Mir/Trans.hs [hunk 9]
```diff
@@ -1973,14 +1974,41 @@ genFn :: HasCallStack =>
...
+      -- uses the untupled form `(T, U, V)`.  `argvars` follows the tupled
+      -- form, but `inputExps` follows the untupled form.  Here we convert
+      -- `inputExps` to match `argvars` by tupling up some of the arguments.
+      --
+      -- Arguments from `spreadArg` onward need to be tupled.  Note that
+      -- `fsspreadarg` is 1-based (it's a MIR `Local` ID, and the first
+      -- argument is local `_1`), but we convert to a 0-based index for
+      -- convenience.
+      let splitIndex = spreadArg - 1
+      when (splitIndex > length inputExps) $
```
Comment (samcowger) [inline crucible-mir/src/Mir/Trans.hs:1996]:
```suggestion
      when (splitIndex >= length inputExps) $
```
IIUC, the case of `splitIndex == length inputExps` is also erroneous, and it gets caught when computing `tupleFieldTys`. However, I think checking for it here would yield a more helpful error message.

File: crucible-mir/src/Mir/TransTy.hs (hunk 4 above)
Comment (samcowger) [inline crucible-mir/src/Mir/TransTy.hs]: Perhaps state that the "special adjustment" is untupling?

File: crucible-mir/src/Mir/Trans.hs [hunk 10]
```diff
@@ -1973,14 +1974,41 @@ genFn :: HasCallStack =>
...
+  let inputExps = toListFC (\atom -> MirExp (R.typeOfAtom atom) (R.AtomExpr atom)) inputs
+  inputExps' <- case sig ^. M.fsabi of
+    M.RustCall (M.RcSpreadArg spreadArg) -> do
+      -- The Rust signature looks like `(T, (U, V))`, but the Crucible version
+      -- uses the untupled form `(T, U, V)`.  `argvars` follows the tupled
+      -- form, but `inputExps` follows the untupled form.  Here we convert
+      -- `inputExps` to match `argvars` by tupling up some of the arguments.
+      --
+      -- Arguments from `spreadArg` onward need to be tupled.  Note that
+      -- `fsspreadarg` is 1-based (it's a MIR `Local` ID, and the first
```
Comment (samcowger) [inline crucible-mir/src/Mir/Trans.hs]: Do you mean `spreadArg` here, instead of `fsspreadarg`?

File: crucible-mir/src/Mir/PP.hs (hunk 3 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/PP.hs:146]: I think the current rendering is fine.  `--print-mir` output is primarily a debugging aid and already only vaguely follows the usual Rust/MIR syntax.  Also, it's important to distinguish the `RcNoSpreadArg` and `RcSpreadArg` in the output.

File: crucible-mir/src/Mir/Trans.hs (hunk 9 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/Trans.hs:1996]: No, `splitIndex == length inputExps` is allowed - it happens when the closure has no arguments.  There is no error when computing `tupleFieldTys` because `tupleFieldTys` looks at `argvars`, not `inputExps`, and `argvars` always has length equal to `splitIndex + 1`.  As noted in the comment above, `inputExps` is based on the untupled signature `fn(T, U, V)`, while `argvars` is based on the tupled signature `fn(T, (U, V))`.  A closure with no arguments would have untupled signature `fn(T)` and tupled signature `fn(T, ())`.

File: crucible-mir/src/Mir/Mir.hs (hunk 1 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/Mir.hs]: Fixed in 35f00b44baee28f5649bba773df875c95d3b71be

File: crucible-mir/src/Mir/TransTy.hs (hunk 4 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/TransTy.hs]: Fixed in 35f00b44baee28f5649bba773df875c95d3b71be

Comment (spernsteiner) [reply crucible-mir/src/Mir/TransTy.hs]: I adjusted this comment slightly in 35f00b44baee28f5649bba773df875c95d3b71be.  I don't think it's necessary to be specific about the adjustment - the point is that this function "does the right thing" in all cases, including `extern "rust-call"`.

File: crucible-mir/src/Mir/Trans.hs (hunk 10 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/Trans.hs]: Fixed in 35f00b44baee28f5649bba773df875c95d3b71be

File: crucible-mir/src/Mir/JSON.hs (hunk 2 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/JSON.hs]: Fixed in 579afd3857198af9fc108870f387483beb58c677

File: crucible-mir/src/Mir/TransTy.hs (hunk 5 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/TransTy.hs]: Fixed in 579afd3857198af9fc108870f387483beb58c677

File: crucible-mir/src/Mir/Trans.hs (hunk 7 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/Trans.hs]: Fixed in 579afd3857198af9fc108870f387483beb58c677

File: crucible-mir/src/Mir/Trans.hs (hunk 8 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/Trans.hs]: Fixed in 579afd3857198af9fc108870f387483beb58c677

File: crucible-mir/src/Mir/Trans.hs (hunk 6 above)
Comment (spernsteiner) [reply crucible-mir/src/Mir/Trans.hs]: Seems potentially useful, so I enabled it for `-d4` and higher in a16f6f8a9d6cf2155fde79e6433f0f3408b44ba9

**Comment by RyanGlScott** [comment]
To answer my question above: yes, this PR does appear to fix #1222, as I can now run the program from https://github.com/GaloisInc/crucible/issues/1222#issuecomment-2233313541 without issue. Moreover, the `crux-mir/test/conc_eval/clos/fn_dyn.rs` test case is very nearly identical to that program, so we have test coverage.

Still, could you amend the PR or commit message to say "Fixes #1222" somewhere so that this connection is more obvious? It might also be worth mentioning this change in the `crucible-mir` changelog.

**Comment by spernsteiner** [comment]
I added some more test cases that cover additional `dyn Fn` variants.

It turns out there are still issues with `Box<dyn FnOnce>` because the trait definition for `FnOnce::call_once` has a signature of `fn(dyn FnOnce, ...)`, which triggers the "standalone use of `dyn`" error.  This would require some additional work, since `dyn Trait` methods with by-value `self` aren't normally supported (if you try to write your own version of `FnOnce`, you won't be able to call it through `Box<dyn MyFnOnce>` like you can with `Box<dyn FnOnce>`).  I've still marked the PR as fixing #1222 because the `FnOnce` case results in a different error message.

There's a separate issue with `Box<dyn Fn>`/`Box<dyn FnMut>`: when the box is dropped, symbolic execution enters infinite recursion in `drop_in_place`.  I think this will likely be fixed by #1445.

I also updated the changelog to mention that calling `dyn Fn` and `dyn FnMut` (but not `dyn FnOnce`) is now supported.

**Review by RyanGlScott — APPROVED** [review]
