### PR TITLE
`crux-llvm`: Add `supply-main-arguments` option

### LINKED ISSUE #812: `crucible-llvm`: Support `main` functions with arguments
`crucible-llvm` currently supports `main` functions with this type signature:

```c
int main() { ... }
```

But not this type signature:

```c
int main(int argc, char **argv) { ... }
```

If you feed the latter program to `crux-llvm`, it will choke thusly:

```
$ crux-llvm test.c                                                                             
[Crux] Using pointer width: 64 for file crux-build/crux~test.bc                                
Function should have no arguments
```

However, it would be useful to support `main` functions of the latter form as well. As one data point, various programs in the SV-COMP benchmark suite, such as [`floats-esbmc-regression/digits_for.c`](https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/floats-esbmc-regression/digits_for.c), use `main` with this type signature. What's more, they never use `argc` nor `argv`, so `crux-llvm` would likely work for these programs if it just passed dummy arguments to `main`!

Some possible ways forward would be:

1. Allow users to configure what arguments to pass to `main`, perhaps through the command line or a configuration file.
2. Teach `crucible-llvm` to pass `argc=1` and `argv=[]` to `main` when it has the latter type signature. There is a question of whether this should be the default behavior, or if this should require users to opt in.

### PR DESCRIPTION
**Pull request by RyanGlScott**
When enabled, `supply-main-arguments` will allow simulating `int main(int argc, char *argv[])` functions by supplying `argc=0` and `argv={}` arguments. This is a very specialized option, but one that ends up being very useful for SV-COMP's purposes, as there are many SV-COMP benchmark programs that define `main` in this way.

Fixes #812.

While I was in town, I spruced up the error message that is given when an entrypoint function has arguments, thereby fixing #816.

### CODE REVIEW

File: crux-llvm/src/Crux/LLVM/Config.hs [hunk 1]
```diff
@@ -82,6 +89,7 @@ data LLVMOptions = LLVMOptions
   , noCompile :: Bool
   , optLevel :: Int
   , symFSRoot :: Maybe FilePath
+  , supplyMainArguments :: Bool
```
Comment (travitch) [inline crux-llvm/src/Crux/LLVM/Config.hs:92]: Do we think that we might want more expressive arguments here in the future? If we made this an ADT, we would have an easy path in the future for just adding a new constructor:
```
data MainArguments = NoArguments -- ^ main ()
                                   | EmptyArguments  -- ^ main (int argc, char* argv[]) where argc = 0
                                   | SomeArguments (NonEmpty String) -- ^ main(int argc, char* argv[]) where argc > 0
```

File: crucible-llvm/src/Lang/Crucible/LLVM/MemModel.hs [hunk 2]
```diff
@@ -543,6 +538,25 @@ ptrMessage msg ptr ty =
           , "  at type " ++ show (G.ppType ty)
           ]
 
+-- | Allocate memory on the stack frame of the currently executing function.
```
Comment (travitch) [inline crucible-llvm/src/Lang/Crucible/LLVM/MemModel.hs:541]: I like giving this a name and exposing it

File: crux-llvm/src/Crux/LLVM/Simulate.hs [hunk 3]
```diff
@@ -228,18 +239,64 @@ prepLLVMModule llvmOpts halloc sym bcFile memVar = do
...
+          sym       = ctx^.ctxSymInterface
+          dl        = llvmDataLayout (trans^.transContext.llvmTypeCtx)
+          tp        = ArrayType 0 (PtrType (MemType i8))
+          tp_sz     = memTypeSize  dl tp
+          alignment = memTypeAlign dl tp
+          loc       = "crux-llvm main(argc, argv) simulation"
+
+      argc <- liftIO $ LLVMPointer <$> natLit sym 0 <*> bvLit sym w (BV.zero w)
+      sz   <- liftIO $ bvLit sym PtrWidth $ bytesToBV PtrWidth tp_sz
+      (argv, mem') <- liftIO $ doAlloca sym mem sz alignment loc
```
Comment (travitch) [inline crux-llvm/src/Crux/LLVM/Simulate.hs:294]: Could you comment on why `doAlloca` over just `doCalloc`?

**Review by travitch — APPROVED** [review]

File: crux-llvm/src/Crux/LLVM/Simulate.hs (hunk 3 above)
Comment (RyanGlScott) [reply crux-llvm/src/Crux/LLVM/Simulate.hs:294]: My goal was to simulate a function that looks roughly like this:

```hs
int crucible_main() {
  int argc = 0;
  char *argv[] = {};
  return main(argc, argv);
}
```

With this in mind, `doAlloca` seemed like a more natural fit, since the LLVM bitcode to create `argv` will use the `alloca` instruction anyway. There's no reason I couldn't use `doCalloc`, I suppose, but then the memory would be on the heap instead of on the stack. That could potentially have ramifications if we ever enter the [`valid-memcleanup`/`valid-memsafety`](https://github.com/GaloisInc/crucible/issues/790) categories (which care a lot about the lifetime of heap-allocated data), so `doAlloca` seemed like the simpler approach.

Having typed all of this out, I should turn this into a comment in the source code as well.

File: crux-llvm/src/Crux/LLVM/Config.hs (hunk 1 above)
Comment (RyanGlScott) [reply crux-llvm/src/Crux/LLVM/Config.hs:92]: You're right—I could foresee someone wanting `SomeArguments` in the future. I can easily turn the `yes`/`no` options for `supply-main-arguments` to `empty`/`none` to keep the door open for extending it in the future. Does `config-schema` allow parsing `empty`, `none`, and something like `["args", "go", "here"]` all in the same option? My understanding of `config-schema`'s [`ValueSpec`](https://hackage.haskell.org/package/config-schema-1.2.2.0/docs/Config-Schema-Spec.html#t:ValueSpec) data type is that it permits this, but I haven't tried implementing something like that yet.

File: crux-llvm/src/Crux/LLVM/Simulate.hs (hunk 3 above)
Comment (travitch) [reply crux-llvm/src/Crux/LLVM/Simulate.hs:294]: I think that is reasonable. `argv` *does* actually live on the stack in most binaries (on Linux, in the aux vector), though in a different spot, so it is reasonable. I was just curious what level of fidelity you were looking for.

File: crux-llvm/src/Crux/LLVM/Config.hs (hunk 1 above)
Comment (travitch) [reply crux-llvm/src/Crux/LLVM/Config.hs:92]: Ah, I'm actually not sure what config-schema supports. I don't see anything quite like that in the exposed API, but that doesn't mean one could definitely not write something like that. No need to do this right now, given that we don't know when we'll need that capability.

Given the structure of `config-schema`, we might instead need to specify command line arguments by supplying multiple `--argument` parameters and just saying that specifying that is mutually-exclusive with `supply-main-arguments`.

File: crux-llvm/src/Crux/LLVM/Simulate.hs (hunk 3 above)
Comment (RyanGlScott) [reply crux-llvm/src/Crux/LLVM/Simulate.hs:311]: I've turned https://github.com/GaloisInc/crucible/pull/826/files#r698825652 into a comment above `checkMainWithArguments`.

File: crux-llvm/src/Crux/LLVM/Config.hs (hunk 1 above)
Comment (RyanGlScott) [reply crux-llvm/src/Crux/LLVM/Config.hs]: I prototyped what this might look like with the following code:

```hs
supplyMainArgumentsSpec :: ValueSpec SupplyMainArguments
supplyMainArgumentsSpec =
  (NoArguments <$ atomSpec "none") <!>
  (EmptyArguments <$ atomSpec "empty") <!>
  (SomeArguments <$> Crux.listSpec Crux.stringSpec)
```

To my delight, this works exactly like I expected it would. In light of this, I'm quite happy with this design, since it should be straightforward to add `SomeArguments` later if we desire it.
