### PR TITLE
`crux-mir`: Support concretizing static references

### LINKED ISSUE #1545: `crux-mir`: Support concretizing static references (i.e., references using `GlobalVar_RefRoot`)
`crux-mir` currently crashes if you try to `concretize` a static reference, as seen in the program below:

```rs
extern crate crucible;
use crucible::*;

#[crux::test]
pub fn f() -> u32 {
    let x: &'static u32 = &0;
    *crucible::concretize(x)
}
```
```
$ cabal -v0 run exe:crux-mir -- test.rs
test.rs:7:6: 7:29: error: in test/d3320d23::f[0]
Unsupported feature: evaluation of GlobalVar_RefRoot is not yet implemented
Details:
  [("throwUnsupported",SrcLoc {srcLocPackage = "crux-mir-0.10.0.0.99-inplace", srcLocModule = "Mir.Overrides", srcLocFile = "src/Mir/Overrides.hs", srcLocStartLine = 353, srcLocStartCol = 9, srcLocEndLine = 353, srcLocEndCol = 25})]test test/d3320d23::f[0]:
```

Where the failing code arises from here:

https://github.com/GaloisInc/crucible/blob/45648cc1ebc834fea38f126e6cac869101189fd0/crux-mir/src/Mir/Overrides.hs#L354

I propose that we make this work by adapting the existing code used to handle `RefCell_RefRoot`s [here](https://github.com/GaloisInc/crucible/blob/45648cc1ebc834fea38f126e6cac869101189fd0/crux-mir/src/Mir/Overrides.hs#L317-L346).

### PR DESCRIPTION
**Pull request by RyanGlScott**
Fixes #1545.

### CODE REVIEW

File: crux-mir/test/symb_eval/concretize/static_ref.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// A regression test for #1545, which ensures that crux-mir is able to
+// concretize static references, i.e., references that are represented with
+// GlobalVar_RefRoot under the hood.
```
Comment (spernsteiner) [inline crux-mir/test/symb_eval/concretize/static_ref.rs:3]:
```suggestion
// A regression test for #1545, which ensures that crux-mir is able to
// concretize references to statics, i.e., references that are represented with
// GlobalVar_RefRoot under the hood.
```

"Static references" could mean `&'static T`, but not all `&'static T` refs are backed by `GlobalVar_RefRoot`:
```Rust
let x: &'static i32 = Box::leak(Box::new(123));
```
This will point to a heap allocation using `RefCell_RefRoot`.

File: crux-mir/test/symb_eval/concretize/static_ref.rs [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+
+extern crate crucible;
+use crucible::*;
+
+#[crux::test]
+pub fn f() -> u32 {
+    let x: &'static u32 = &0;
```
Comment (spernsteiner) [inline crux-mir/test/symb_eval/concretize/static_ref.rs]: `&0` is guaranteed to get promoted to a static (by my read of the [Rust Reference](https://doc.rust-lang.org/reference/destructors.html#constant-promotion)), but it might be clearer to explicitly write a `static` item and take its address, since references to `static` items are the ones that use `GlobalVar_RefRoot`.

Comment (RyanGlScott) [reply crux-mir/test/symb_eval/concretize/static_ref.rs]: I've changed the test case to the following:

```rs
static X: u32 = 0;

#[crux::test]
pub fn f() -> u32 {
    *crucible::concretize(&X)
}
```
