### PR TITLE
`{crucible,crux}-llvm`: Adapt to elliottt/llvm-pretty#118

### LINKED ISSUE #1145: Adapt `crucible-llvm` to more `llvm-pretty` functions requiring implicit `?config` parameters
When we next bump the `llvm-pretty` submodule, we will likely need to bring in the changes from https://github.com/elliottt/llvm-pretty/pull/118 and friends. Among other changes, these PRs add implicit `?config :: Config` constraints to functions that did not have them before, such as `ppType`. This means that `crucible-llvm` will fail to compile if we don't make any other changes:

```
[22 of 53] Compiling Lang.Crucible.LLVM.Errors.MemoryError ( src/Lang/Crucible/LLVM/Errors/MemoryError.hs, interpreted )

src/Lang/Crucible/LLVM/Errors/MemoryError.hs:160:73: error:
    • Could not deduce: ?config::L.Config
        arising from a use of ‘L.ppType’
      from the context: IsExpr (SymExpr sym)
        bound by the type signature for:
                   ppMemoryOp :: forall sym (w :: GHC.TypeNats.Nat) ann.
                                 IsExpr (SymExpr sym) =>
                                 MemoryOp sym w -> Doc ann
        at src/Lang/Crucible/LLVM/Errors/MemoryError.hs:122:1-63
    • In the first argument of ‘viaShow’, namely ‘(L.ppType sig)’
      In the second argument of ‘(<+>)’, namely ‘viaShow (L.ppType sig)’
      In the expression:
        "Attempting to load callable function with type:"
          <+> viaShow (L.ppType sig)
    |
160 |   vsep [ "Attempting to load callable function with type:" <+> viaShow (L.ppType sig)
    |                                                                         ^^^^^^^^
```

This is only one example of the breakage—there are others that lie in wait after this one.

Note that we are mainly using the `llvm-pretty` printer in `crucible-llvm` for the sake of defining `Show` instances and creating error messages, not for creating machine-readable LLVM code. As a result, I think it would suffice to wrap each of these functions in a `ppLLVM` function that uses the `Config` corresponding to the most recent LLVM version that `llvm-pretty` supports.

### PR DESCRIPTION
**Pull request by RyanGlScott**
This patch:

* Bumps the `llvm-pretty` and `llvm-pretty-bc-parser` submodules to recent commits that include the changes from https://github.com/elliottt/llvm-pretty/pull/118.
* Introduces a `ppLLVMLatest` combinator to `Lang.Crucible.LLVM.PrettyPrint` that prints a `Fmt` value (from `Text.LLVM.PP`) using the latest version of LLVM that `llvm-pretty` supports.
* Uses `ppLLVMLatest` in the appropriate places to fix compilation errors.

Fixes #1145.

### CODE REVIEW

File: crucible-llvm/src/Lang/Crucible/LLVM/Globals.hs [hunk 1]
```diff
@@ -133,8 +134,7 @@ makeGlobalMap ctx m = foldl' addAliases globalMap (Map.toList (llvmGlobalAliases
            ++ ": "
            ++ err)
      where showSymbol sym =
-             show $ let ?config = LPP.Config False False False
-                    in LPP.ppSymbol $ sym
+             show $ ppLLVMLatest $ LPP.ppSymbol $ sym
```
Comment (RyanGlScott) [inline crucible-llvm/src/Lang/Crucible/LLVM/Globals.hs:137]: I opted to change the `Config` used here for consistency's sake. The `ppSymbol` function doesn't make use of any `Config`-specific options anyway.

File: crucible-llvm/src/Lang/Crucible/LLVM/PrettyPrint.hs [hunk 2]
```diff
@@ -40,3 +45,14 @@ ppVectorType n e = angles (pretty (toInteger n) <+> pretty 'x' <+> e)
 
 ppIntVector :: Integral a => Natural -> a -> Doc ann
 ppIntVector n w = ppVectorType n (ppIntType w)
+
+-- | Pretty-print an LLVM-related AST in accordance with the latest LLVM version
+-- that @llvm-pretty@ currently supports (i.e., the value of 'llvmVlatest'.)
```
Comment (langston-barrett) [inline crucible-llvm/src/Lang/Crucible/LLVM/PrettyPrint.hs:50]: Does this need to be qualified to show up as a link?
```suggestion
-- that @llvm-pretty@ currently supports (i.e., the value of 'LLVM.llvmVlatest'.)
```

**Review by langston-barrett — APPROVED** [review]
Might be worth creating helpers such as `ppTyped = ppLLVMLatest L.ppType`, etc.

**Review by kquick — APPROVED** [review]
