### PR TITLE
`crux-mir`: Always print error messages upon `mir-json` compilation failures

### LINKED ISSUE #1084: Make `crux-mir` print compiler errors from `rustc`
If you run `crux-mir` on a malformed `.rs` file, e.g.,

```rs
syntax_error()
```

Then by default, this is the error that `crux-mir` will give you:

```
$ cabal run exe:crux-mir -- err.rs
user error (Error 101 while running mir-json on err.rs)
```

It's only if you run `crux-mir` with higher verbosity settings that the actual problem is made clear:

```
$ cabal run exe:crux-mir -- err.rs --sim-verbose=3
Generating err.mir
error: expected one of `!` or `::`, found `(`
 --> err.rs:1:13
  |
1 | syntax_error()
  |             ^ expected one of `!` or `::`

error: aborting due to previous error

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorGuaranteed(())', src/bin/mir-json.rs:65:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
user error (Error 101 while running mir-json on err.rs)
```

In this small example, it's somewhat obvious what the issue is, but in larger examples, it can be befuddling to see nothing but `Error 101` until you realize what is actually going on. It would be preferable for `crux-mir` to print these sorts of `rustc` errors by default, without needing to resort to higher verbosity levels.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Previously, compiler errors would only be shown if the user explicitly opted into them using `--sim-verbose=3` or higher. This is a fairly counterintuitive default setting, as it means that users who run `crux-mir` on a malformed Rust file (a fairly common occurrence) will have to scratch their heads until they realize why `crux-mir` isn't showing them what went wrong.

This patch changes `crux-mir` to unconditionally show compiler error messages when compilation fails, regardless of the `--sim-verbose` level. I have adopted a convention for formatting the standard output/standard error of `mir-json` that is very similar to what `crux-llvm` uses when it unsucessfully compiles something using a `clang` subprocess.

Fixes #1084.

### CODE REVIEW

File: crux-mir/src/Mir/Generate.hs [hunk 1]
```diff
@@ -77,23 +77,26 @@ compileMirJson keepRlib quiet rustFile = do
...
     case ec of
-        ExitFailure cd -> fail $
-            "Error " ++ show cd ++ " while running mir-json on " ++ rustFile
+        ExitFailure cd -> fail $ unlines $
+            [ "Error " ++ show cd ++ " while running mir-json on " ++ rustFile
+            , "*** Standard out:"
+            ] ++
+            [ "   " ++ l | l <- lines sout ] ++
+            [ "*** Standard error:" ] ++
+            [ "   " ++ l | l <- lines serr ]
```
Comment (spernsteiner) [inline crux-mir/src/Mir/Generate.hs]: FWIW I don't think rustc or mir-json prints anything to stdout during normal builds.  Rustc errors/warnings and env_logger messages all go to stderr.

File: crux-mir/src/Mir/Generate.hs [hunk 2]
```diff
@@ -77,23 +77,26 @@ compileMirJson keepRlib quiet rustFile = do
...
             , "-Z", "ub-checks=false"
             , "-o", outFile]
-    let cp' = if not quiet then cp else
-            (cp { Proc.std_out = Proc.NoStream, Proc.std_err = Proc.NoStream })
-    ec <- Proc.withCreateProcess cp' $ \_ _ _ ph -> Proc.waitForProcess ph
+    (ec, sout, serr) <- Proc.readCreateProcessWithExitCode cp ""
     case ec of
-        ExitFailure cd -> fail $
-            "Error " ++ show cd ++ " while running mir-json on " ++ rustFile
+        ExitFailure cd -> fail $ unlines $
```
Comment (samcowger) [inline crux-mir/src/Mir/Generate.hs]: Embedding this output in `fail` seems to subject it to `crux-mir`'s colorization, which feels like a bummer, given how richly colored `rustc` errors are. Local experimentation suggests we could avoid this if we
- add `--color=always` to the `mir-json` invocation,
- `hPutStrLn stderr` this message, and
- fail out afterwards with `fail "compilation error"` or some such simple message.

Does that sound plausible and worthwhile to you?

**Review by samcowger — APPROVED** [review]
Thank you for this!

File: crux-mir/src/Mir/Generate.hs (hunk 1 above)
Comment (RyanGlScott) [reply crux-mir/src/Mir/Generate.hs]: Indeed, I think you're right. I mainly did it this way to be consistent with `crux-llvm`, but I think it would be reasonable to deviate from `crux-llvm`'s conventions a little bit here for the sake of making the output a bit more concise.

File: crux-mir/src/Mir/Generate.hs (hunk 2 above)
Comment (RyanGlScott) [reply crux-mir/src/Mir/Generate.hs]: I like this train of thought, although I'm a bit cautious about being overly opinionated on which flags to pass `rustc`. In particular, always passing `--color=always` to `rustc` would mean that the compiler output would _always_ be colorized, even if a user set the [`NO_COLOR` environment variable](https://no-color.org/). Even if https://github.com/GaloisInc/crucible/issues/1556 were implemented, a user would have no way to override this setting, since passing `--color` to `rustc` twice causes an error, e.g.,

```
$ rustc --color=always --color=never test.rs
error: Option 'color' given more than once
```

Perhaps the thing to do here is to control whether `--color=always` is passed or not based on Crux's `--no-color` flag. That should be reasonably consistent with how other bits of colorized output work in Crux.

Comment (samcowger) [reply crux-mir/src/Mir/Generate.hs]: Ah, fair - that sounds like a reasonable approach to me. Is that simple enough to fold into this PR, or would you prefer that we open an issue about it and address it separately?

Comment (RyanGlScott) [reply crux-mir/src/Mir/Generate.hs]: I'll try implementing this as part of this PR.

Comment (RyanGlScott) [reply crux-mir/src/Mir/Generate.hs]: I've pushed a new version of the PR which preserves colors in `rustc` error messages. Let me know what you think.

Comment (samcowger) [reply crux-mir/src/Mir/Generate.hs]: LGTM, much appreciated!
