### PR TITLE
`crucible-wasm`: Build and test with the latest `haskell-wasm` commit

### LINKED ISSUE #1227: `crucible-wasm`: Make it build with the latest `haskell-wasm` commit
Currently, `crucible-wasm` will not build if you update the `haskell-wasm` submodule to the latest commit (at the time of writing, this is https://github.com/SPY/haskell-wasm/commit/23aef00097039faf240746a64c5f9ac2c90efdf6):

```
[2 of 8] Compiling Lang.Crucible.Wasm.Memory ( src/Lang/Crucible/Wasm/Memory.hs, interpreted )

src/Lang/Crucible/Wasm/Memory.hs:35:1: warning: [-Wunused-imports]
    The import of ‘What4.InterpretedFloatingPoint’ is redundant
      except perhaps to import instances from ‘What4.InterpretedFloatingPoint’
    To import instances alone, use: import What4.InterpretedFloatingPoint()
   |
35 | import What4.InterpretedFloatingPoint
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[3 of 8] Compiling Lang.Crucible.Wasm.Instantiate ( src/Lang/Crucible/Wasm/Instantiate.hs, interpreted )

src/Lang/Crucible/Wasm/Instantiate.hs:389:27: error:
    Variable not in scope: memIndex :: Wasm.MemoryIndex
    Suggested fix:
      Perhaps use ‘LBS.elemIndex’ (imported from Data.ByteString.Lazy)
    |
389 |      case resolveMemIndex memIndex i of
    |                           ^^^^^^^^

src/Lang/Crucible/Wasm/Instantiate.hs:390:82: error:
    Variable not in scope: memIndex
    Suggested fix:
      Perhaps use ‘LBS.elemIndex’ (imported from Data.ByteString.Lazy)
    |
390 |        Nothing -> instErr ("Could not resolve memory index " <> fromString (show memIndex))
    |                                                                                  ^^^^^^^^

src/Lang/Crucible/Wasm/Instantiate.hs:395:26: error:
    Variable not in scope: offset :: Wasm.Expression
    Suggested fix:
      Perhaps use ‘Wasm.offset’ (imported from Language.Wasm.Structure)
    |
395 |              evalConst i offset >>= \case
    |                          ^^^^^^

src/Lang/Crucible/Wasm/Instantiate.hs:404:36: error:
    Variable not in scope: offset :: Wasm.Expression
    Suggested fix:
      Perhaps use ‘Wasm.offset’ (imported from Language.Wasm.Structure)
    |
404 |   do I32Val tblOff <- evalConst im offset
    |                                    ^^^^^^

src/Lang/Crucible/Wasm/Instantiate.hs:420:85: error:
    Variable not in scope: tableIndex :: Wasm.TableIndex
    Suggested fix:
      Perhaps use ‘baseIndex’ (imported from Data.Parameterized.Context)
    |
420 |     do (Wasm.TableType (Wasm.Limit lmin _) Wasm.FuncRef, addr) <- resolveTableIndex tableIndex im
    |                                                                                     ^^^^^^^^^^

src/Lang/Crucible/Wasm/Instantiate.hs:422:49: error:
    Variable not in scope: funcIndexes :: t0 a1
    |
422 |        guard (toInteger off + toInteger (length funcIndexes) <= toInteger lmin)
    |                                                 ^^^^^^^^^^^

src/Lang/Crucible/Wasm/Instantiate.hs:423:55: error:
    Variable not in scope: funcIndexes :: [Wasm.FuncIndex]
    |
423 |        funaddrs <- mapM (\i -> resolveFuncIndex i im) funcIndexes
    |                                                       ^^^^^^^^^^^
```

We should investigate these and make adapt `crucible-wasm` accordingly.

### PR DESCRIPTION
**Pull request by RyanGlScott**
This PR contains a series of small patches that makes `crucible-wasm` compile with the latest `haskell-wasm` commit (at the time of writing, this is https://github.com/SPY/haskell-wasm/commit/23aef00097039faf240746a64c5f9ac2c90efdf6). Moreover, in places where `crucible-wasm`'s test suite was lacking, I have added some additional test cases to ensure that any changes introduced in this PR did not cause inadvertent regressions.

Most of the changes on the `haskell-wasm` side are to adapt to new features in Wasm 2.0. Generally speaking, I have not gone through the effort of implementing support for all of Wasm 2.0's new features, instead leaving that as future work. One particularly notable feature which I did not implement is support for reference types and values, which would require a non-trivial amount of work to support on the `crucible-wasm` side. See #1228.

After these changes, we will finally be building against a version of `haskell-wasm` that support GHC 9.8. This will allow us to then add support for GHC 9.8 elsewhere in the `crucible` repo.

Fixes #1227.

### CODE REVIEW

File: crucible-wasm/src/Lang/Crucible/Wasm/Translate.hs [hunk 1]
```diff
@@ -622,11 +622,11 @@ genInstruction genReturn im st ctrlStack instr =
             Just (ConstantGlobal _) -> panic "genInstruction: SetGlobal" ["setGlobal of constant global"]
             Just (MutableGlobal gv) -> writeGlobal gv =<< checkStackVal (globalType gv) =<< popStack
 
-    Wasm.CurrentMemory ->
+    Wasm.MemorySize ->
```
Comment (mccleeary-galois) [inline crucible-wasm/src/Lang/Crucible/Wasm/Translate.hs:625]: Should we add the following to a ticket as well so it doesn't get lost?

> I have not added support for the `memory.fill`, `memory.copy`,
  `memory.init`, or `data.drop` instructions, all of which are new in Wasm 2.0.

**Review by mccleeary-galois — APPROVED** [review]
Not an expert, but this all seems reasonable steps towards support of WASM 2.0.

File: crucible-wasm/src/Lang/Crucible/Wasm/Translate.hs (hunk 1 above)
Comment (RyanGlScott) [reply crucible-wasm/src/Lang/Crucible/Wasm/Translate.hs:625]: I've opened https://github.com/GaloisInc/crucible/issues/1233 for this.
