### PR TITLE
`crucible-syntax`: Allow exotic characters in fresh atom names

### LINKED ISSUE #1024: `crucible-syntax`: `let ... fresh` fails to parse when identifier contains a hyphen
Consider the following `crucible-syntax` program, which does work:

```racket
(defun @test () Unit
  (start start:
    (let i1 (fresh Bool))
    (let i-2 #t)
    (return ())))
```

This shows that you can (1) initialize values with `fresh` symbolic values, and (2) define names with hyphens. If you combine these two things, however:

```racket
(defun @test () Unit
  (start start:
    (let i-3 (fresh Bool))
    (return ())))
```

Then it fails to parse for some mysterious reason:

```
$ cabal run exe:crucible -- check test.cbl
At test.cbl:3:14, expected an atom but got (fresh Bool)
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Previously, we used `userSymbol` to create fresh atom names, but `userSymbol` will fail if given any characters outside of the very narrow range of characters allowed in What4 solver names. Instead, we now use `safeSymbol`, which will Z-encode any unallowable characters into something that is allowed in a What4 solver name. This ensures (among other things) that we can write things like `(let i-3 (fresh Bool))`, as hyphens are not allowed in What4 solver names without Z-encoding them.

Fixes #1024.

### CODE REVIEW

File: crucible-syntax/src/Lang/Crucible/Syntax/Concrete.hs [hunk 1]
```diff
@@ -1563,22 +1563,26 @@ atomSetter (AtomName anText) =
...
+         case t of
+           Some (FloatRepr fi) ->
+             Some <$>
+               freshAtom loc (FreshFloat fi (Just nm))
+           Some NatRepr ->
+             Some <$> freshAtom loc (FreshNat (Just nm))
+           Some tp
+             | AsBaseType bt <- asBaseType tp ->
+                 Some <$> freshAtom loc (FreshConstant bt (Just nm))
+             | otherwise -> describe "atomic type" $ empty
```
Comment (sauclovian-g) [inline crucible-syntax/src/Lang/Crucible/Syntax/Concrete.hs:1585]: I don't think you want two layers of describe here...

Comment (sauclovian-g) [reply crucible-syntax/src/Lang/Crucible/Syntax/Concrete.hs:1585]: ...although looking more carefully I notice this isn't new behavior. Might want to fix it up anyway.

**Review by sauclovian-g — APPROVED** [review]

File: crucible-syntax/src/Lang/Crucible/Syntax/Concrete.hs (hunk 1 above)
Comment (RyanGlScott) [reply crucible-syntax/src/Lang/Crucible/Syntax/Concrete.hs:1584]: Good point. I think calling `describe` twice made more sense back when this function had two separate ways to fail, with one of the failures being `userSymbol`-related. Now that the only way to fail is by constructing a non-atomic type, I think that should be the only place we call `describe`. I've pushed a new version which does this.
