### PR TITLE
`crucible-mir`: Limited support for translating coroutines

### LINKED ISSUE #1626: `crucible-mir`: Emit a proper translation error when simulating coroutines
Simulating the following program with `crux-mir`:

```rs
#![feature(coroutines, coroutine_trait, stmt_expr_attributes)]

use std::ops::Coroutine;
use std::pin::Pin;

#[crux::test]
pub fn f() {
    let mut coroutine = #[coroutine] || {
        yield 1;
        return "foo"
    };

    let p = Pin::new(&mut coroutine);
    p.resume(());
}
```

Yields the following, terrible error message:

```
$ cabal -v0 run exe:crux-mir -- test.rs
user error (JSON decoding of test.all.mir failed: Error in $.fns[0].body.blocks[0].block.data[0].rhs.akind: unimp: Coroutine)
```

At a minimum, we should emit a translation error here instead of a confusing JSON parsing-related error message. This would also allow `crux-mir` to simulate more programs where coroutines are used, but not directly from the function being used as a simulation entrypoint.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Although we stop short of full support for `async`-related coroutine code (see issue #1369 for that task), `crucible-mir` now has the ability to translate coroutine closure expression and a limited ability to translate coroutine expressions. This means that we can translate code involving coroutines without `crucible-mir` crashing outright, instead giving a nicer `Coroutines not currently supported` error message in the event that a user tries to simulate a coroutine expression.

This bumps the `mir-json` submodule to bring in the corresponding changes from https://github.com/GaloisInc/mir-json/pull/205. As a consequence, this requires bumping the supported MIR JSON schema version.

Fixes #1626.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Note that this does not add any test cases. This is for an unfortunate reason: any test case that would exercise the new functionality would require Rust language features that are not available in `--edition=2015`, which is what the test suite uses when compiling `conc_eval` test cases with `rustc`. See https://github.com/GaloisInc/crucible/issues/1668. We would need to address that issue first if we wanted to test this new code.

That being said, even if we did, the results wouldn't be very interesting. Essentially all programs one could write involving `coroutine`s will still crash at simulation time anyway, as we do not currently have a good story for translating coroutine aggregates.

**Review by spernsteiner — APPROVED** [review]

File: crucible-mir/src/Mir/Trans.hs [hunk 1]
```diff
@@ -1395,6 +1400,12 @@ evalRval (M.CopyForDeref lv) = evalLvalue lv
 evalRval (M.ShallowInitBox {}) = mirFail
     "evalRval: ShallowInitBox not supported"
 
+evalTupleRval :: HasCallStack => [Operand] -> MirGenerator h s ret (MirExp s)
+evalTupleRval ops = do
+  let tys = map typeOf ops
+  exps <- mapM evalOperand ops
+  buildTupleMaybeM tys (map Just exps)
```
Comment (samcowger) [inline crucible-mir/src/Mir/Trans.hs]: Save a few characters:
```suggestion
  buildTupleM tys exps
```

File: crucible-mir/src/Mir/TransTy.hs [hunk 2]
```diff
@@ -1537,9 +1544,15 @@ initialValue (M.TyDowncast {}) = return Nothing
...
 initialValue (M.TyConst {}) = return Nothing
 initialValue (M.TyLifetime {}) = return Nothing
+initialValue (M.TyCoroutine {}) = return Nothing
 initialValue (M.TyErased {}) = return Nothing
 initialValue (M.TyInterned {}) = return Nothing
 
+initialTupleValue ::
+  HasCallStack => [M.Ty] -> MirGenerator h s ret (Maybe (MirExp s))
+initialTupleValue tys =
+  Just . MirExp MirAggregateRepr <$> mirAggregate_uninit_constSize (fromIntegral $ length tys)
```
Comment (samcowger) [inline crucible-mir/src/Mir/TransTy.hs:1555]: Using `length tys` as the aggregate size implicitly hardcodes type size to be 1 byte; would you mind leaving a note to that effect?
```suggestion
initialTupleValue ::
  HasCallStack => [M.Ty] -> MirGenerator h s ret (Maybe (MirExp s))
initialTupleValue tys =
  -- TODO: hardcoded size=1
  Just . MirExp MirAggregateRepr <$> mirAggregate_uninit_constSize (fromIntegral $ length tys)
```

**Review by samcowger — APPROVED** [review]
