### PR TITLE
`crux-llvm-test`: Sanitize SMT formulas in `--get-abducts` output

### LINKED ISSUE #1086: `crux-llvm`: Abduction tests are sensitive to CVC5 versions
If I run the abduction-related `crux-llvm` tests using `cvc5-1.0.5`, then it fails with:

<details>

```
$ cabal run test:crux-llvm-test -- -p abd
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
*** Longer running test skipped; set CI_TEST_LEVEL=1 env var to enable
crux-llvm
  clang 14.0.0-1ubuntu1
    abd-test-file-32.c
      cvc5
        loop
          recent-clang
            cvc5 1.0.5
              abd-test-file-32
                abd-test-file-32 crux run:      OK (0.27s)
                abd-test-file-32 crux output:   FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-file-32.cvc5.good)
                             and actual (test-data/golden/abd-test-file-32.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-file-32.c:11:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 3 fact(s) would entail the goal
                      F-expect>|[Crux]   * (= x #b00000000000000000000000000000001)
                      F-actual>|[Crux]   * (bvult #b00000000000000000000000001100100 x)
                      F-expect>|[Crux]   * (= x #b00000000000000000000000000000000)
                      F-actual>|[Crux]   * (bvult #b00000000000000000000000001100011 x)
                      F-expect>|[Crux]   * (bvult x #b00000000000000000000000001100011)
                      F-actual>|[Crux]   * (= #b00000000000000000000000000000000 x)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loop.recent-clang.cvc5 1.0.5.abd-test-file-32.abd-test-file-32 crux output/' to rerun this test only.
        loopmerge
          recent-clang
            cvc5 1.0.5
              abd-test-file-32
                abd-test-file-32 crux run:      OK (0.28s)
                abd-test-file-32 crux output:   FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-file-32.cvc5.good)
                             and actual (test-data/golden/abd-test-file-32.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-file-32.c:11:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 3 fact(s) would entail the goal
                      F-expect>|[Crux]   * (= x #b00000000000000000000000000000001)
                      F-actual>|[Crux]   * (bvult #b00000000000000000000000001100100 x)
                      F-expect>|[Crux]   * (= x #b00000000000000000000000000000000)
                      F-actual>|[Crux]   * (bvult #b00000000000000000000000001100011 x)
                      F-expect>|[Crux]   * (bvult x #b00000000000000000000000001100011)
                      F-actual>|[Crux]   * (= #b00000000000000000000000000000000 x)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loopmerge.recent-clang.cvc5 1.0.5.abd-test-file-32.abd-test-file-32 crux output/' to rerun this test only.
    abd-test-file-8.c
      cvc5
        loop
          recent-clang
            cvc5 1.0.5
              abd-test-file-8
                abd-test-file-8 crux run:       OK (0.31s)
                abd-test-file-8 crux output:    FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-file-8.cvc5.good)
                             and actual (test-data/golden/abd-test-file-8.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-file-8.c:11:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 3 fact(s) would entail the goal
                      F-expect>|[Crux]   * (bvult x #b00000001)
                      F-actual>|[Crux]   * (= x #b00000000)
                      F        |[Crux]   * (bvult #b01100100 x)
                      F        |[Crux]   * (= #b00000001 x)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loop.recent-clang.cvc5 1.0.5.abd-test-file-8.abd-test-file-8 crux output/' to rerun this test only.
        loopmerge
          recent-clang
            cvc5 1.0.5
              abd-test-file-8
                abd-test-file-8 crux run:       OK (0.30s)
                abd-test-file-8 crux output:    FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-file-8.cvc5.good)
                             and actual (test-data/golden/abd-test-file-8.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-file-8.c:11:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 3 fact(s) would entail the goal
                      F-expect>|[Crux]   * (bvult x #b00000001)
                      F-actual>|[Crux]   * (= x #b00000000)
                      F        |[Crux]   * (bvult #b01100100 x)
                      F        |[Crux]   * (= #b00000001 x)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loopmerge.recent-clang.cvc5 1.0.5.abd-test-file-8.abd-test-file-8 crux output/' to rerun this test only.
    abd-test-maxint-32.c
      cvc5
        loop
          recent-clang
            cvc5 1.0.5
              abd-test-maxint-32
                abd-test-maxint-32 crux run:    OK (0.26s)
                abd-test-maxint-32 crux output: FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-maxint-32.cvc5.good)
                             and actual (test-data/golden/abd-test-maxint-32.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-maxint-32.c:6:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 2 fact(s) would entail the goal
                      F-expect>|[Crux]   * (bvult x #b00000000000000000000000000000001)
                      F-actual>|[Crux]   * (= #b00000000000000000000000000000001 x)
                      F-expect>|[Crux]   * (bvult x #b11111111111111111111111111111111)
                      F-actual>|[Crux]   * (= x #b00000000000000000000000000000000)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loop.recent-clang.cvc5 1.0.5.abd-test-maxint-32.abd-test-maxint-32 crux output/' to rerun this test only.
        loopmerge
          recent-clang
            cvc5 1.0.5
              abd-test-maxint-32
                abd-test-maxint-32 crux run:    OK (0.26s)
                abd-test-maxint-32 crux output: FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-maxint-32.cvc5.good)
                             and actual (test-data/golden/abd-test-maxint-32.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-maxint-32.c:6:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 2 fact(s) would entail the goal
                      F-expect>|[Crux]   * (bvult x #b00000000000000000000000000000001)
                      F-actual>|[Crux]   * (= #b00000000000000000000000000000001 x)
                      F-expect>|[Crux]   * (bvult x #b11111111111111111111111111111111)
                      F-actual>|[Crux]   * (= x #b00000000000000000000000000000000)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loopmerge.recent-clang.cvc5 1.0.5.abd-test-maxint-32.abd-test-maxint-32 crux output/' to rerun this test only.
    abd-test-trans-8.c
      cvc5
        loop
          recent-clang
            cvc5 1.0.5
              abd-test-trans-8
                abd-test-trans-8 crux run:      OK (1.50s)
                abd-test-trans-8 crux output:   FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-trans-8.cvc5.good)
                             and actual (test-data/golden/abd-test-trans-8.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-trans-8.c:9:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 3 fact(s) would entail the goal
                      F        |[Crux]   * (= z y)
                      F        |[Crux]   * (= (bvashr x z) #b00000001)
                      F-expect>|[Crux]   * (bvult z (bvlshr x y))
                      F-actual>|[Crux]   * (= (bvor x z) y)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loop.recent-clang.cvc5 1.0.5.abd-test-trans-8.abd-test-trans-8 crux output/' to rerun this test only.
        loopmerge
          recent-clang
            cvc5 1.0.5
              abd-test-trans-8
                abd-test-trans-8 crux run:      OK (1.50s)
                abd-test-trans-8 crux output:   FAIL
                  test/Test.hs:268:
                  MISMATCH for expected (test-data/golden/abd-test-trans-8.cvc5.good)
                             and actual (test-data/golden/abd-test-trans-8.cvc5.cvc5.out) output:
                      F        |[Crux] Found counterexample for verification goal
                      F        |[Crux]   test-data/golden/abd-test-trans-8.c:9:0: error: in main
                      F        |[Crux]   crucible_assert
                      F        |[Crux] 
                      F        |[Crux]   One of the following 3 fact(s) would entail the goal
                      F        |[Crux]   * (= z y)
                      F        |[Crux]   * (= (bvashr x z) #b00000001)
                      F-expect>|[Crux]   * (bvult z (bvlshr x y))
                      F-actual>|[Crux]   * (= (bvor x z) y)
                      F        |[Crux] Overall status: Invalid.
                  
                  Use -p '/abd/&&/loopmerge.recent-clang.cvc5 1.0.5.abd-test-trans-8.abd-test-trans-8 crux output/' to rerun this test only.

8 out of 16 tests failed (4.69s)
```
</details>

This is a bit surprising, since these tests pass on CI. But that is because the CI is using `cvc5-1.0.2`, revealing that these tests are extremely sensitive to the choice of CVC5 version being used to test with.

This state of affairs doesn't seem tenable, as it means that we would potentially need different golden output for each CVC5 version that we want to support. In some cases, the reported abducts are simply in a different order, but other times, one CVC5 version might report a completely different abduct than a different CVC5 version. As a result, we can't work around this issue by simply sorting the abducts.

The best idea that I have for making this work is to have `crux-llvm`'s test suite scrub the particular abduct values from the golden output so that the choice of abducts does not affect whether the test passes or fails. This would at least ensure that all of the relevant code paths involved in the `--get-abducts` flag continue to work without needing an explosion of different golden output combinations.

### PR DESCRIPTION
**Pull request by RyanGlScott**
Unfortunately, the abducts (i.e., SMT formulas) that CVC5 suggests are wildly sensitive to the particular CVC5 and LLVM versions being used, which makes the abducts poorly suited to golden test output. This patch scrubs the SMT formulas from `crux`'s `--get-abducts` output to avoid this issue.

Fixes #1086.

### CODE REVIEW

File: crux/src/Crux/FormatOut.hs [hunk 1]
```diff
@@ -84,6 +84,9 @@ sayWhatFailedGoals skipIncompl showVars allGls =
                     else [] 
                  -- print abducts, if any
                  ++ if s /= [] then
+                      -- NB: If you update the contents of this error message,
+                      -- make sure to update the corresponding regex that
+                      -- checks for this in crux-llvm/test/Test.hs.
                       PP.pretty ("One of the following " ++ show (length s) ++ " fact(s) would entail the goal")
```
Comment (kquick) [inline crux/src/Crux/FormatOut.hs:90]: This is a nit, but while we're in the area and since this is using `prettyprinter` to format the message, what do you think about using the latter's `plural` function instead of the text "fact(s)" here?

**Review by kquick — APPROVED** [review]
It's unfortunate that the output is unstable, but this seems like a reasonable way to address it.

File: crux/src/Crux/FormatOut.hs (hunk 1 above)
Comment (RyanGlScott) [reply crux/src/Crux/FormatOut.hs:90]: That sounds fine to me. We'd need to make the regex slightly more complicated to accommodate the possibility of "fact" vs. "facts", but that is a small price to pay.
